require "user.lazy"
require "user.options"
require "user.keymaps"
require "user.colorscheme"
  require "user.lsp"
  require "user.treesitter"
  require "user.telescope"
  require "impatient"
  require "user.toggleterm"
  require "user.transparent"
  require "user.projections"
  require "user.lspsaga"
  require "user.whichkey"
  require "user.mini-animate"
  require "user.telekasten"
  require "user.cmp"

require "plugins.configs.bufferline"

