require "user.lazy"
require "user.options"
require "user.keymaps"
require "user.colorscheme"
require "user.lsp"
require "user.treesitter"
require "impatient"
require "user.cmp"

require "plugins.configs.bufferline"
